- name: Get HostName
  hosts: all
  tasks:
    - name: Get hostname
      shell: echo $HOSTNAME
      register: result
    - name: Print Value
      debug:
        var:  result
    - name: Get OS release
      shell: |
          cat /etc/os-release
      register: OSVersionInfo
    - name: Get OSVersionInfo
      debug: 
        msg: "{{ OSVersionInfo.stdout }}"
    - name: Get Firewall status
      shell:  systemctl status firewalld
      register: firewallresult
    - name: Get Firewall status result
      debug:
        msg: "{{ firewallresult.stdout }}"
    - name: collect facts about system services
      service_facts:
      register: services_state
    - name: Debug
      ansible.builtin.debug:
        var: ansible_facts.services['iptables.service']
    