- name: Get HostName
  hosts: all
  tasks:
    - name: Get hostname
      shell: echo $HOSTNAME
      register: result
    - name: Print Value
      debug:
        var:  result
    - name: Get OS release
      shell: |
          cat /etc/os-release
      register: OSVersionInfo
    - name: Get OSVersionInfo
      debug: 
        msg: "{{ OSVersionInfo.stdout }}"